name: workspaceinfo

on:
  push:
    branches:
    - github
  workflow_dispatch:
   
env:
#  image: ${{ github.event.client_payload.img }}
#  sha: ${{ github.event.client_payload.sha }}
 filename: ${{ github.workspace }}/dev/deploy.yaml
 image: hello:1.0.0
 
jobs:
  workspaceinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
         ref: github
        
#       - run: echo 'workspace value in  is ${{ github.workspace }}'
      - run: echo 'branch ref name is ${{ github.ref_name }}'
#       - run: echo 'env path is ${{ github.env }}'
      - run: echo 'filename from env is  ${{ env.filename }}'
      - run: ls ${{ github.workspace }}/dev
      - run: echo "the ls in echo is \n$(ls {{ env.filename }})"
      - run: sed -i 's/image.*/image:\ ${{ env.image }}/' ${{ env.filename }}
      - run: echo "new file   $(cat ${{ env.filename }})"
      - name: push
        uses: github-actions-x/commit@v2.9
        
        
