name: kk Dispatch
on:
  workflow_dispatch:
   inputs:
      Version:
        description: 'The revision to rollback to'
        required: true

 
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.client_payload.ref }}
      - run: |
           echo "The version is ${{ github.event.inputs.Version }}"
