name: kk Dispatch
on:
  repository_dispatch:
    types: kk
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # with:
        #   ref: ${{ github.event.client_payload.ref }}
      - run: |
         echo ${{ github.event.client_payload.img }}
         echo ${{ github.event.client_payload.Image_version }}
         echo ${{ github.event.client_payload.sha }}
         echo ${{ github.event.client_payload.event_type2}}
