name: publish

on:
  push:
    branches:
    - push
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false 
        fetch-depth: 0 
        ref: push
    - name: Create local changes
      run: touch file1
    - name: Commit & Push changes
      uses: actions-js/push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: push
        
