name: Repository Dispatch
on:
  repository_dispatch:
    types: workflow_api

    
env:
 Image_name: ${{ github.event.client_payload.img }}
 Image_version: ${{ github.event.client_payload.Image_version }}
 Filename: ${{ github.workspace }}/dev/deploy.yaml

jobs:
  Update_Image_version:
   runs-on: ubuntu-latest 
   steps:
      - uses: actions/checkout@v3
        with:
         persist-credentials: false 
         fetch-depth: 0 
         ref: main
      - name: New Image
        id: job1
        
        run: |
         echo 'Workflow trigger by Image_name  -->  ${{ env.Image_name }}:${{ env.Image_version }}'
         echo 'Workflow trigger by event type  -->  ${{ github.event.event_type }}
     #    echo 'Workflow trigger by event name  -->  ${{ github.event}}
         sed -i 's|image: http/${{ env.Image_name }}:.*|image: http/${{ env.Image_name }}:${{ env.Image_version }}|' ${{ env.Filename }}
     #   echo 'Updated deploy.yaml'
      #  cat ${{ env.Filename}}
  
      - name: Commit & Push changes
        run: |
          cat ${{ env.Filename}}
      -  uses: actions-js/push@master
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           branch: main
           message: 'Auto commit from github action'

  
   

        
