name: publish

on:
  push:
    branches:
    - push
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
      with:
        ref: push
    - name: creat file
      run:  touch {{github.workspace }}/file1.yaml
    - run: ls {{github.workspace }}
    - name: push
      uses: github-actions-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'push'
        commit-message: 'publish'
        force-add: 'true'
        files: file1.yaml
        
