name: Another Workflow
on:
  # repository_dispatch:
  #   type: workflow_api

  workflow_dispatch:
   inputs:
      revision:
        description: 'The revision to rollback to'
        required: true

      

  
     
  # push:
  #   branches:
  #    - roll-back
permissions:
 contents: write
    
env:
# Branch: ${{ github.event.inputs.branch }}
 revision: ${{ github.event.inputs.revision }}
#Image_version: ${{ github.event.client-payload.Image_version }}
# Image_version1: hello
# R1: ${{ github.event.client-payload.R1 }}
# R2: ${{ github.event.client-payload.R2 }}
 
jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # with:
        #    ref: roll-back
        #    fetch-depth: 0

      - name: echo
        run: | 
        
         echo "ROLLback revision is ${{ env.revision }}"
         # echo "Image_Name is ${{ env.Image_Name }}"
         # echo "Image_version is ${{ env.Image_version }}"
         # echo "Image_version1is ${{ env.Image_version1 }}"
         # echo "R1is ${{ env.R1 }}"
         # echo "R2 ${{ env.R2 }}"
         

   
      # - name: Get latest release 
      #   uses: rez0n/actions-github-release@main
      #   id: node_release
      #   with:
      #    token: ${{ secrets.GITHUB_TOKEN }}
      #    repository: "kjs2021/maven"
      #    type: "latest"

      # - name: echo tag before release created
      #   run: 
      #    echo " ROLL_Image= ${{ steps.node_release.outputs.release }}">> Githuboutput
      #    echo " current release ${{ steps.node_release.outputs.release_id }}"

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}

      # - name: Get latest release afternew creation
      #   uses: rez0n/actions-github-release@main
      #   id: node_release1
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     repository: "kjs2021/maven"
      #     type: "latest"



      # - name: echo tag after release created
      #   run: 
      #    echo " current tag is ${{ steps.node_release1.outputs.release }}"
      #    echo " current release ${{ steps.node_release1.outputs.release_id }}"
        

      # - name: Rolls back to a certain version
      #   uses: fivebluepetals/rollback-action@v1.0
      #   with:
      #     branch: ${{ env.Branch }}
      #     revision: ${{ steps.node_release.outputs.release }}
