name: Roll-back
on:
  workflow_dispatch:
   inputs:
      revision:
        description: 'The revision to rollback to'
        required: true

      branch:
        description: 'The branch that the rollback affects'
        required: true
  push:
    branches:
     - roll-back
    
env:
 Branch: ${{ github.event.inputs.Branch }}
 Revision: ${{ github.event.inputs.revision }}

jobs:
  Rollback:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
           ref: roll-back
           fetch-depth: 0

      - name: echo
        run: 
         echo " branchname is ${{ env.Branch }}"
         echo " revision is ${{ env.Revision }}"

      # - name: Get Current Release
      #   id: get_current_release
      #   uses: joutvhu/get-release@v1
      #   with:
      #     debug: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get latest release 
        uses: rez0n/actions-github-release@main
        id: node_release
        with:
         token: ${{ secrets.GITHUB_TOKEN }}
         repository: "kjs2021/maven"
         type: "latest"



      - name: echo tag
        run: 
         echo " current tag is ${{ steps.node_release.outputs.release }}"
         echo " current release ${{ steps.node_release.outputs.release_id }}"
        

      # - name: Rolls back to a certain version
      #   uses: fivebluepetals/rollback-action@v1.0
      #   with:
      #     branch: ${{ github.event.inputs.branch }}
      #     revision: ${{ github.event.inputs.revision }}
