name: terraform workflow

on:
  push:
    branches:
    - main
    paths:
    - Function/*
  workflow_dispatch:

 
env:
  FunctionName: ${{ github.event.head_commit.message }}
#   Title: ${{ github.event.pull_request.title }}

    
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - run: |
       - run: |
         echo `terraform apply  - replace ="module.cloud_function.${{ env.FunctionName }}.cloudfunction2"`
         echo "The name of the pusher: ${{ github.event.pusher.name }}"
         echo "The email of the pusher: ${{ github.event.pusher.email }}"
         echo "actor-id: ${{ github.actor_id }}"
         echo "actorname: ${{ github.actor }}" 
      #   echo " running terraform Title for function ${{ env.Title }}"
