name: terraform workflow

on:
  push:
    branches:
    - main
    paths:
    - MyFirstFolder/*
  workflow_dispatch:

env:
  FunctionName: ${{ github.event.head_commit.message }}
  FunctionName1: Revert
  


    
jobs:

  # checkout:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: teraaform-apply
      id: apply
      run: |
         echo 'terraform apply  - replace ="module.cloud_function.${{ env.FunctionName1 }}.cloudfunction2"'
      #    echo 'terraform apply  - replace ="module.cloud_function.${{ env.FunctionName2 }}.cloudfunction2"'
      #    echo "The name of the pusher: ${{ github.event.pusher.name }}"
      #    echo "The email of the pusher: ${{ github.event.pusher.email }}"
      #    echo "${{toJSON(github.event)}}"
      # #   echo " running terraform Title for function ${{ env.Title }}"

    # Revert commit (only should run on failure of some phase in a CI/CD pipeline)
  auto-revert-commit:
    needs: Terraform
    runs-on: ubuntu-latest
    if: always() && (needs.Terraform.result == 'failure')
    steps:
      - name: Automatic Commit Revert
        uses: 'tofu-apis/revert-commit-action@v0.0.37'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          is-push-enabled: 'true'  
    

  # PULLrequest-Revert:
  #  runs-on: ubuntu-latest
  #  if: ${{ failure () }}
  #  needs: [Terraform]
  #  steps:
  #   - name: Checkout
  #     uses: actions/checkout@v2
  #   - name: Revert pull request
  #     id: pullest
  #     uses: repo-sync/pull-request@v2
  #     with:
  #       destination_branch: "revert"
  #       pr_title:  "revert"      
  #       pr_label: "revert"
  #       pr_reviewer: "kjs2021"                      
  #       pr_assignee: "kjs2021" 
  #       pr_body: |                                       
  #         /revert <commit_sha>
          
  # revert-commit:
  #   runs-on: ubuntu-latest
   
  #   if: contains(github.event.comment.body, '/revert')

  #   steps:
  #     - name: Checkout latest code
  #       uses: actions/checkout@v2
  #     - name: Automatic Revert
  #       uses: srt32/revert@v0.0.1
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
