name: terraform workflow

on:
  push:
    branches:
    - main
    paths:
    - Function
  workflow_dispatch:

    
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo " running terraform"
