name: terraform workflow

on:
  push:
    branches:
    - main
    paths:
    - Function
  workflow_dispatch:
env:
  FunctionName: ${{ github.event.head_commit.message }}

    
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - run: |
       echo " running terraform for function ${{ env.FunctionName }}"
