name: terraform workflow

on:
  push:
    branches:
    - test-branch
    paths:
    - Function
  workflow_dispatch:
env:  
    
jobs:
    init:
      run-on:
      steps:
       - name: terraform init
         run: |
         echo ' running terraform'
