name: terraform workflow

on:
  push:
    branches:
    - main
    paths:
    - Function/*
  workflow_dispatch:

env:
  FunctionName: ${{ github.event.head_commit.message }}
#   FunctionName2: ${{ github.event.commits[0].message }}
#   Title: ${{ github.event.pull_request.title }}
concurrency:
  #group: ${{ github.head_ref || github.run_id }}
  group: terraform
  cancel-in-progress: false

    
jobs:
  Terraform:
    runs-on: ubuntu-latest
    steps:
    - name: teraaform-apply
      run: |
         echo 'terraform apply  - replace ="module.cloud_function.${{ env.FunctionName }}.cloudfunction2"'
         echo "The name of the pusher: ${{ github.event.pusher.name }}"
         echo "The email of the pusher: ${{ github.event.pusher.email }}"
         echo "${{toJSON(github.event)}}"
      #   echo " running terraform Title for function ${{ env.Title }}"
