name: Workflow example

on:
  push:
    branches:
    - test-branch
    paths:
    - Function/*
  workflow_dispatch:
  
env:
  FunctionName: ${{ github.event.head_commit.message }}
    
jobs:
 job1:
  runs-on: ubuntu-latest
#   outputs:
#       Function1: ${{ steps.step1.outputs.Function_name }}
  steps:
      - name: updated terrafrom
        run: |
         echo  "${{ env.FunctionName }}Function  will be updated by terraform"
         
         
#       - id: step1
#         run: echo "Function_name=${{ github.event.head_commit.message }}" >> "$GITHUB_OUTPUT"
        
 job2:
    runs-on: ubuntu-latest
    needs: job1
#     env:
#           OUTPUT1: ${{needs.job1.outputs.Function1}}
    steps:        
      - run: |
         echo 'terraform apply - replace ="${{ env.FunctionName }}"'
