name: Workflow example

on:
  push:
    branches:
    - test-branch
    paths:
    - Function/*
  workflow_dispatch:
  
env:
  FunctionName: ${{ github.event.head_commit.message }}
concurrency:
  #group: ${{ github.head_ref || github.run_id }}
  group: terraform
  cancel-in-progress: true
 
jobs:
 job1:
  runs-on: ubuntu-latest

  steps:
      - name: updated terrafrom
        run: |
         echo  "${{ env.FunctionName }} Function  will be updated by terraform"
      
 job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:        
      - run: |
         echo 'terraform apply  - replace ="module.cloud_function.${{ env.FunctionName }}.cloudfunction2"'
         echo "The name of the pusher: ${{ github.event.pusher.name }}"
         echo "The email of the pusher: ${{ github.event.pusher.email }}"
         echo "${{ github.actor_id }}"
         echo "${{ github.actor }}" 
