name: Workflow example

on:

  push:
    branches:
    - test-branch
    paths:
    - Function/*
  workflow_dispatch:
    
jobs:
 job1:
  runs-on: ubuntu-latest
  outputs:
      Function1: ${{ steps.step1.outputs.Function_name }}
  steps:
      - name: updated terrafrom
        run: |
         echo  "New Function  to update by terraform"
         echo "${{ github.event.head_commit.message }}"
         
      - id: step1
        run: echo "Function_name=${{ github.event.head_commit.message }}" >> "$GITHUB_OUTPUT"
        
 job2:
    runs-on: ubuntu-latest
    needs: job1
    env:
          OUTPUT1: ${{needs.job1.outputs.Function1}}
    steps:        
      - run: |
         echo "${{ env.OUTPUT1 }}"
