name: Workflow example

on:

  push:
    branches:
    - test-branch
    paths:
    - hello
  workflow_dispatch:
    
jobs:
 trigger:
  runs-on: ubuntu-latest
  steps:
      - name: updated terrafrom
        run: |
         echo  "New Image will be  terraform"
